// Code generated by "pipeline"; DO NOT EDIT.
package keys

import (
	"github.com/genshinsim/gcsim/pkg/core/attributes"
)

const (
	TestCharDoNotUse Char = iota + TravelerDelim + 1
	Albedo
	Alhaitham
	Aloy
	Amber
	Arlecchino
	Ayaka
	Ayato
	Baizhu
	Barbara
	Beidou
	Bennett
	Candace
	Charlotte
	Chasca
	Chevreuse
	Chiori
	Chongyun
	Citlali
	Clorinde
	Collei
	Cyno
	Dehya
	Diluc
	Diona
	Dori
	Emilie
	Escoffier
	Eula
	Faruzan
	Fischl
	Freminet
	Furina
	Gaming
	Ganyu
	Gorou
	Heizou
	Hutao
	Itto
	Jean
	Kaeya
	Kaveh
	Kazuha
	Keqing
	Kinich
	Kirara
	Klee
	Kokomi
	Kuki
	Lanyan
	Layla
	Lisa
	Lynette
	Lyney
	Mavuika
	Mika
	Mizuki
	Mona
	Mualani
	Nahida
	Navia
	Neuvillette
	Nilou
	Ningguang
	Noelle
	Ororon
	Qiqi
	Raiden
	Razor
	Rosaria
	Sara
	Sayu
	Sethos
	Shenhe
	Sigewinne
	Skirk
	Sucrose
	Tartaglia
	Thoma
	Tighnari
	Venti
	Wanderer
	Wriothesley
	Xiangling
	Xianyun
	Xiao
	Xilonen
	Xingqiu
	Xinyan
	YaeMiko
	Yanfei
	Yaoyao
	Yelan
	Yoimiya
	Yunjin
	Zhongli
	EndCharKeys
)

func init() {
	charNames[Albedo] = "albedo"
	charPrettyName[Albedo] = "Albedo"
	CharKeyToEle[Albedo] = attributes.ElementRock

	charNames[Alhaitham] = "alhaitham"
	charPrettyName[Alhaitham] = "Alhaitham"
	CharKeyToEle[Alhaitham] = attributes.ElementGrass

	charNames[Aloy] = "aloy"
	charPrettyName[Aloy] = "Aloy"
	CharKeyToEle[Aloy] = attributes.ElementIce

	charNames[Amber] = "amber"
	charPrettyName[Amber] = "Amber"
	CharKeyToEle[Amber] = attributes.ElementFire

	charNames[Arlecchino] = "arlecchino"
	charPrettyName[Arlecchino] = "Arlecchino"
	CharKeyToEle[Arlecchino] = attributes.ElementFire

	charNames[Ayaka] = "ayaka"
	charPrettyName[Ayaka] = "Ayaka"
	CharKeyToEle[Ayaka] = attributes.ElementIce

	charNames[Ayato] = "ayato"
	charPrettyName[Ayato] = "Ayato"
	CharKeyToEle[Ayato] = attributes.ElementWater

	charNames[Baizhu] = "baizhu"
	charPrettyName[Baizhu] = "Baizhu"
	CharKeyToEle[Baizhu] = attributes.ElementGrass

	charNames[Barbara] = "barbara"
	charPrettyName[Barbara] = "Barbara"
	CharKeyToEle[Barbara] = attributes.ElementWater

	charNames[Beidou] = "beidou"
	charPrettyName[Beidou] = "Beidou"
	CharKeyToEle[Beidou] = attributes.ElementElectric

	charNames[Bennett] = "bennett"
	charPrettyName[Bennett] = "Bennett"
	CharKeyToEle[Bennett] = attributes.ElementFire

	charNames[Candace] = "candace"
	charPrettyName[Candace] = "Candace"
	CharKeyToEle[Candace] = attributes.ElementWater

	charNames[Charlotte] = "charlotte"
	charPrettyName[Charlotte] = "Charlotte"
	CharKeyToEle[Charlotte] = attributes.ElementIce

	charNames[Chasca] = "chasca"
	charPrettyName[Chasca] = "Chasca"
	CharKeyToEle[Chasca] = attributes.ElementWind

	charNames[Chevreuse] = "chevreuse"
	charPrettyName[Chevreuse] = "Chevreuse"
	CharKeyToEle[Chevreuse] = attributes.ElementFire

	charNames[Chiori] = "chiori"
	charPrettyName[Chiori] = "Chiori"
	CharKeyToEle[Chiori] = attributes.ElementRock

	charNames[Chongyun] = "chongyun"
	charPrettyName[Chongyun] = "Chongyun"
	CharKeyToEle[Chongyun] = attributes.ElementIce

	charNames[Citlali] = "citlali"
	charPrettyName[Citlali] = "Citlali"
	CharKeyToEle[Citlali] = attributes.ElementIce

	charNames[Clorinde] = "clorinde"
	charPrettyName[Clorinde] = "Clorinde"
	CharKeyToEle[Clorinde] = attributes.ElementElectric

	charNames[Collei] = "collei"
	charPrettyName[Collei] = "Collei"
	CharKeyToEle[Collei] = attributes.ElementGrass

	charNames[Cyno] = "cyno"
	charPrettyName[Cyno] = "Cyno"
	CharKeyToEle[Cyno] = attributes.ElementElectric

	charNames[Dehya] = "dehya"
	charPrettyName[Dehya] = "Dehya"
	CharKeyToEle[Dehya] = attributes.ElementFire

	charNames[Diluc] = "diluc"
	charPrettyName[Diluc] = "Diluc"
	CharKeyToEle[Diluc] = attributes.ElementFire

	charNames[Diona] = "diona"
	charPrettyName[Diona] = "Diona"
	CharKeyToEle[Diona] = attributes.ElementIce

	charNames[Dori] = "dori"
	charPrettyName[Dori] = "Dori"
	CharKeyToEle[Dori] = attributes.ElementElectric

	charNames[Emilie] = "emilie"
	charPrettyName[Emilie] = "Emilie"
	CharKeyToEle[Emilie] = attributes.ElementGrass

	charNames[Escoffier] = "escoffier"
	charPrettyName[Escoffier] = "Escoffier"
	CharKeyToEle[Escoffier] = attributes.ElementIce

	charNames[Eula] = "eula"
	charPrettyName[Eula] = "Eula"
	CharKeyToEle[Eula] = attributes.ElementIce

	charNames[Faruzan] = "faruzan"
	charPrettyName[Faruzan] = "Faruzan"
	CharKeyToEle[Faruzan] = attributes.ElementWind

	charNames[Fischl] = "fischl"
	charPrettyName[Fischl] = "Fischl"
	CharKeyToEle[Fischl] = attributes.ElementElectric

	charNames[Freminet] = "freminet"
	charPrettyName[Freminet] = "Freminet"
	CharKeyToEle[Freminet] = attributes.ElementIce

	charNames[Furina] = "furina"
	charPrettyName[Furina] = "Furina"
	CharKeyToEle[Furina] = attributes.ElementWater

	charNames[Gaming] = "gaming"
	charPrettyName[Gaming] = "Gaming"
	CharKeyToEle[Gaming] = attributes.ElementFire

	charNames[Ganyu] = "ganyu"
	charPrettyName[Ganyu] = "Ganyu"
	CharKeyToEle[Ganyu] = attributes.ElementIce

	charNames[Gorou] = "gorou"
	charPrettyName[Gorou] = "Gorou"
	CharKeyToEle[Gorou] = attributes.ElementRock

	charNames[Heizou] = "heizou"
	charPrettyName[Heizou] = "Heizou"
	CharKeyToEle[Heizou] = attributes.ElementWind

	charNames[Hutao] = "hutao"
	charPrettyName[Hutao] = "Hutao"
	CharKeyToEle[Hutao] = attributes.ElementFire

	charNames[Itto] = "itto"
	charPrettyName[Itto] = "Itto"
	CharKeyToEle[Itto] = attributes.ElementRock

	charNames[Jean] = "jean"
	charPrettyName[Jean] = "Jean"
	CharKeyToEle[Jean] = attributes.ElementWind

	charNames[Kaeya] = "kaeya"
	charPrettyName[Kaeya] = "Kaeya"
	CharKeyToEle[Kaeya] = attributes.ElementIce

	charNames[Kaveh] = "kaveh"
	charPrettyName[Kaveh] = "Kaveh"
	CharKeyToEle[Kaveh] = attributes.ElementGrass

	charNames[Kazuha] = "kazuha"
	charPrettyName[Kazuha] = "Kazuha"
	CharKeyToEle[Kazuha] = attributes.ElementWind

	charNames[Keqing] = "keqing"
	charPrettyName[Keqing] = "Keqing"
	CharKeyToEle[Keqing] = attributes.ElementElectric

	charNames[Kinich] = "kinich"
	charPrettyName[Kinich] = "Kinich"
	CharKeyToEle[Kinich] = attributes.ElementGrass

	charNames[Kirara] = "kirara"
	charPrettyName[Kirara] = "Kirara"
	CharKeyToEle[Kirara] = attributes.ElementGrass

	charNames[Klee] = "klee"
	charPrettyName[Klee] = "Klee"
	CharKeyToEle[Klee] = attributes.ElementFire

	charNames[Kokomi] = "kokomi"
	charPrettyName[Kokomi] = "Kokomi"
	CharKeyToEle[Kokomi] = attributes.ElementWater

	charNames[Kuki] = "kuki"
	charPrettyName[Kuki] = "Kuki"
	CharKeyToEle[Kuki] = attributes.ElementElectric

	charNames[Lanyan] = "lanyan"
	charPrettyName[Lanyan] = "Lanyan"
	CharKeyToEle[Lanyan] = attributes.ElementWind

	charNames[Layla] = "layla"
	charPrettyName[Layla] = "Layla"
	CharKeyToEle[Layla] = attributes.ElementIce

	charNames[Lisa] = "lisa"
	charPrettyName[Lisa] = "Lisa"
	CharKeyToEle[Lisa] = attributes.ElementElectric

	charNames[Lynette] = "lynette"
	charPrettyName[Lynette] = "Lynette"
	CharKeyToEle[Lynette] = attributes.ElementWind

	charNames[Lyney] = "lyney"
	charPrettyName[Lyney] = "Lyney"
	CharKeyToEle[Lyney] = attributes.ElementFire

	charNames[Mavuika] = "mavuika"
	charPrettyName[Mavuika] = "Mavuika"
	CharKeyToEle[Mavuika] = attributes.ElementFire

	charNames[Mika] = "mika"
	charPrettyName[Mika] = "Mika"
	CharKeyToEle[Mika] = attributes.ElementIce

	charNames[Mizuki] = "mizuki"
	charPrettyName[Mizuki] = "Mizuki"
	CharKeyToEle[Mizuki] = attributes.ElementWind

	charNames[Mona] = "mona"
	charPrettyName[Mona] = "Mona"
	CharKeyToEle[Mona] = attributes.ElementWater

	charNames[Mualani] = "mualani"
	charPrettyName[Mualani] = "Mualani"
	CharKeyToEle[Mualani] = attributes.ElementWater

	charNames[Nahida] = "nahida"
	charPrettyName[Nahida] = "Nahida"
	CharKeyToEle[Nahida] = attributes.ElementGrass

	charNames[Navia] = "navia"
	charPrettyName[Navia] = "Navia"
	CharKeyToEle[Navia] = attributes.ElementRock

	charNames[Neuvillette] = "neuvillette"
	charPrettyName[Neuvillette] = "Neuvillette"
	CharKeyToEle[Neuvillette] = attributes.ElementWater

	charNames[Nilou] = "nilou"
	charPrettyName[Nilou] = "Nilou"
	CharKeyToEle[Nilou] = attributes.ElementWater

	charNames[Ningguang] = "ningguang"
	charPrettyName[Ningguang] = "Ningguang"
	CharKeyToEle[Ningguang] = attributes.ElementRock

	charNames[Noelle] = "noelle"
	charPrettyName[Noelle] = "Noelle"
	CharKeyToEle[Noelle] = attributes.ElementRock

	charNames[Ororon] = "ororon"
	charPrettyName[Ororon] = "Ororon"
	CharKeyToEle[Ororon] = attributes.ElementElectric

	charNames[Qiqi] = "qiqi"
	charPrettyName[Qiqi] = "Qiqi"
	CharKeyToEle[Qiqi] = attributes.ElementIce

	charNames[Raiden] = "raiden"
	charPrettyName[Raiden] = "Raiden"
	CharKeyToEle[Raiden] = attributes.ElementElectric

	charNames[Razor] = "razor"
	charPrettyName[Razor] = "Razor"
	CharKeyToEle[Razor] = attributes.ElementElectric

	charNames[Rosaria] = "rosaria"
	charPrettyName[Rosaria] = "Rosaria"
	CharKeyToEle[Rosaria] = attributes.ElementIce

	charNames[Sara] = "sara"
	charPrettyName[Sara] = "Sara"
	CharKeyToEle[Sara] = attributes.ElementElectric

	charNames[Sayu] = "sayu"
	charPrettyName[Sayu] = "Sayu"
	CharKeyToEle[Sayu] = attributes.ElementWind

	charNames[Sethos] = "sethos"
	charPrettyName[Sethos] = "Sethos"
	CharKeyToEle[Sethos] = attributes.ElementElectric

	charNames[Shenhe] = "shenhe"
	charPrettyName[Shenhe] = "Shenhe"
	CharKeyToEle[Shenhe] = attributes.ElementIce

	charNames[Sigewinne] = "sigewinne"
	charPrettyName[Sigewinne] = "Sigewinne"
	CharKeyToEle[Sigewinne] = attributes.ElementWater

	charNames[Skirk] = "skirk"
	charPrettyName[Skirk] = "Skirk"
	CharKeyToEle[Skirk] = attributes.ElementIce

	charNames[Sucrose] = "sucrose"
	charPrettyName[Sucrose] = "Sucrose"
	CharKeyToEle[Sucrose] = attributes.ElementWind

	charNames[Tartaglia] = "tartaglia"
	charPrettyName[Tartaglia] = "Tartaglia"
	CharKeyToEle[Tartaglia] = attributes.ElementWater

	charNames[Thoma] = "thoma"
	charPrettyName[Thoma] = "Thoma"
	CharKeyToEle[Thoma] = attributes.ElementFire

	charNames[Tighnari] = "tighnari"
	charPrettyName[Tighnari] = "Tighnari"
	CharKeyToEle[Tighnari] = attributes.ElementGrass

	charNames[Venti] = "venti"
	charPrettyName[Venti] = "Venti"
	CharKeyToEle[Venti] = attributes.ElementWind

	charNames[Wanderer] = "wanderer"
	charPrettyName[Wanderer] = "Wanderer"
	CharKeyToEle[Wanderer] = attributes.ElementWind

	charNames[Wriothesley] = "wriothesley"
	charPrettyName[Wriothesley] = "Wriothesley"
	CharKeyToEle[Wriothesley] = attributes.ElementIce

	charNames[Xiangling] = "xiangling"
	charPrettyName[Xiangling] = "Xiangling"
	CharKeyToEle[Xiangling] = attributes.ElementFire

	charNames[Xianyun] = "xianyun"
	charPrettyName[Xianyun] = "Xianyun"
	CharKeyToEle[Xianyun] = attributes.ElementWind

	charNames[Xiao] = "xiao"
	charPrettyName[Xiao] = "Xiao"
	CharKeyToEle[Xiao] = attributes.ElementWind

	charNames[Xilonen] = "xilonen"
	charPrettyName[Xilonen] = "Xilonen"
	CharKeyToEle[Xilonen] = attributes.ElementRock

	charNames[Xingqiu] = "xingqiu"
	charPrettyName[Xingqiu] = "Xingqiu"
	CharKeyToEle[Xingqiu] = attributes.ElementWater

	charNames[Xinyan] = "xinyan"
	charPrettyName[Xinyan] = "Xinyan"
	CharKeyToEle[Xinyan] = attributes.ElementFire

	charNames[YaeMiko] = "yaemiko"
	charPrettyName[YaeMiko] = "Yae Miko"
	CharKeyToEle[YaeMiko] = attributes.ElementElectric

	charNames[Yanfei] = "yanfei"
	charPrettyName[Yanfei] = "Yanfei"
	CharKeyToEle[Yanfei] = attributes.ElementFire

	charNames[Yaoyao] = "yaoyao"
	charPrettyName[Yaoyao] = "Yaoyao"
	CharKeyToEle[Yaoyao] = attributes.ElementGrass

	charNames[Yelan] = "yelan"
	charPrettyName[Yelan] = "Yelan"
	CharKeyToEle[Yelan] = attributes.ElementWater

	charNames[Yoimiya] = "yoimiya"
	charPrettyName[Yoimiya] = "Yoimiya"
	CharKeyToEle[Yoimiya] = attributes.ElementFire

	charNames[Yunjin] = "yunjin"
	charPrettyName[Yunjin] = "Yunjin"
	CharKeyToEle[Yunjin] = attributes.ElementRock

	charNames[Zhongli] = "zhongli"
	charPrettyName[Zhongli] = "Zhongli"
	CharKeyToEle[Zhongli] = attributes.ElementRock
}
