// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/genshinsim/gcsim/pkg/core (interfaces: Core)
//
// Generated by this command:
//
//	mockgen -destination=mock_core.go -package=mock github.com/genshinsim/gcsim/pkg/core Core
//

// Package mock is a generated GoMock package.
package mock

import (
	rand "math/rand"
	reflect "reflect"

	core "github.com/genshinsim/gcsim/pkg/core"
	event "github.com/genshinsim/gcsim/pkg/core/event"
	glog "github.com/genshinsim/gcsim/pkg/core/glog"
	info "github.com/genshinsim/gcsim/pkg/core/info"
	keys "github.com/genshinsim/gcsim/pkg/core/keys"
	task "github.com/genshinsim/gcsim/pkg/core/task"
	geometry "github.com/genshinsim/gcsim/pkg/geometry"
	gomock "go.uber.org/mock/gomock"
)

// MockCore is a mock of Core interface.
type MockCore struct {
	ctrl     *gomock.Controller
	recorder *MockCoreMockRecorder
	isgomock struct{}
}

// MockCoreMockRecorder is the mock recorder for MockCore.
type MockCoreMockRecorder struct {
	mock *MockCore
}

// NewMockCore creates a new mock instance.
func NewMockCore(ctrl *gomock.Controller) *MockCore {
	mock := &MockCore{ctrl: ctrl}
	mock.recorder = &MockCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCore) EXPECT() *MockCoreMockRecorder {
	return m.recorder
}

// ActiveCharacter mocks base method.
func (m *MockCore) ActiveCharacter() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveCharacter")
	ret0, _ := ret[0].(int)
	return ret0
}

// ActiveCharacter indicates an expected call of ActiveCharacter.
func (mr *MockCoreMockRecorder) ActiveCharacter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveCharacter", reflect.TypeOf((*MockCore)(nil).ActiveCharacter))
}

// AddGadget mocks base method.
func (m *MockCore) AddGadget(g core.Gadget) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddGadget", g)
}

// AddGadget indicates an expected call of AddGadget.
func (mr *MockCoreMockRecorder) AddGadget(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGadget", reflect.TypeOf((*MockCore)(nil).AddGadget), g)
}

// AddPlayerShield mocks base method.
func (m *MockCore) AddPlayerShield(shd core.Shield) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPlayerShield", shd)
}

// AddPlayerShield indicates an expected call of AddPlayerShield.
func (mr *MockCoreMockRecorder) AddPlayerShield(shd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlayerShield", reflect.TypeOf((*MockCore)(nil).AddPlayerShield), shd)
}

// CanBeDefenseHalt mocks base method.
func (m *MockCore) CanBeDefenseHalt() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanBeDefenseHalt")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanBeDefenseHalt indicates an expected call of CanBeDefenseHalt.
func (mr *MockCoreMockRecorder) CanBeDefenseHalt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanBeDefenseHalt", reflect.TypeOf((*MockCore)(nil).CanBeDefenseHalt))
}

// ClosestEnemy mocks base method.
func (m *MockCore) ClosestEnemy(pos geometry.Point) core.Enemy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosestEnemy", pos)
	ret0, _ := ret[0].(core.Enemy)
	return ret0
}

// ClosestEnemy indicates an expected call of ClosestEnemy.
func (mr *MockCoreMockRecorder) ClosestEnemy(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosestEnemy", reflect.TypeOf((*MockCore)(nil).ClosestEnemy), pos)
}

// ClosestEnemyWithinArea mocks base method.
func (m *MockCore) ClosestEnemyWithinArea(ap info.AttackPattern, filter func(core.Enemy) bool) core.Enemy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosestEnemyWithinArea", ap, filter)
	ret0, _ := ret[0].(core.Enemy)
	return ret0
}

// ClosestEnemyWithinArea indicates an expected call of ClosestEnemyWithinArea.
func (mr *MockCoreMockRecorder) ClosestEnemyWithinArea(ap, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosestEnemyWithinArea", reflect.TypeOf((*MockCore)(nil).ClosestEnemyWithinArea), ap, filter)
}

// ClosestGadget mocks base method.
func (m *MockCore) ClosestGadget(pos geometry.Point) core.Gadget {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosestGadget", pos)
	ret0, _ := ret[0].(core.Gadget)
	return ret0
}

// ClosestGadget indicates an expected call of ClosestGadget.
func (mr *MockCoreMockRecorder) ClosestGadget(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosestGadget", reflect.TypeOf((*MockCore)(nil).ClosestGadget), pos)
}

// ConstructCountByType mocks base method.
func (m *MockCore) ConstructCountByType(t info.GeoConstructType) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructCountByType", t)
	ret0, _ := ret[0].(int)
	return ret0
}

// ConstructCountByType indicates an expected call of ConstructCountByType.
func (mr *MockCoreMockRecorder) ConstructCountByType(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructCountByType", reflect.TypeOf((*MockCore)(nil).ConstructCountByType), t)
}

// ConstructExpiry mocks base method.
func (m *MockCore) ConstructExpiry(t info.GeoConstructType) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructExpiry", t)
	ret0, _ := ret[0].(int)
	return ret0
}

// ConstructExpiry indicates an expected call of ConstructExpiry.
func (mr *MockCoreMockRecorder) ConstructExpiry(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructExpiry", reflect.TypeOf((*MockCore)(nil).ConstructExpiry), t)
}

// Events mocks base method.
func (m *MockCore) Events() *event.System {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events")
	ret0, _ := ret[0].(*event.System)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockCoreMockRecorder) Events() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockCore)(nil).Events))
}

// F mocks base method.
func (m *MockCore) F() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "F")
	ret0, _ := ret[0].(int)
	return ret0
}

// F indicates an expected call of F.
func (mr *MockCoreMockRecorder) F() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "F", reflect.TypeOf((*MockCore)(nil).F))
}

// GetCharacter mocks base method.
func (m *MockCore) GetCharacter(index int) core.Character {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacter", index)
	ret0, _ := ret[0].(core.Character)
	return ret0
}

// GetCharacter indicates an expected call of GetCharacter.
func (mr *MockCoreMockRecorder) GetCharacter(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacter", reflect.TypeOf((*MockCore)(nil).GetCharacter), index)
}

// GetCharacterByKey mocks base method.
func (m *MockCore) GetCharacterByKey(key keys.Char) core.Character {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByKey", key)
	ret0, _ := ret[0].(core.Character)
	return ret0
}

// GetCharacterByKey indicates an expected call of GetCharacterByKey.
func (mr *MockCoreMockRecorder) GetCharacterByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByKey", reflect.TypeOf((*MockCore)(nil).GetCharacterByKey), key)
}

// GetCharacterByTarget mocks base method.
func (m *MockCore) GetCharacterByTarget(key keys.Target) core.Character {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByTarget", key)
	ret0, _ := ret[0].(core.Character)
	return ret0
}

// GetCharacterByTarget indicates an expected call of GetCharacterByTarget.
func (mr *MockCoreMockRecorder) GetCharacterByTarget(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByTarget", reflect.TypeOf((*MockCore)(nil).GetCharacterByTarget), key)
}

// GetEnemies mocks base method.
func (m *MockCore) GetEnemies() []core.Enemy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnemies")
	ret0, _ := ret[0].([]core.Enemy)
	return ret0
}

// GetEnemies indicates an expected call of GetEnemies.
func (mr *MockCoreMockRecorder) GetEnemies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnemies", reflect.TypeOf((*MockCore)(nil).GetEnemies))
}

// GetEnemy mocks base method.
func (m *MockCore) GetEnemy(i int) core.Enemy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnemy", i)
	ret0, _ := ret[0].(core.Enemy)
	return ret0
}

// GetEnemy indicates an expected call of GetEnemy.
func (mr *MockCoreMockRecorder) GetEnemy(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnemy", reflect.TypeOf((*MockCore)(nil).GetEnemy), i)
}

// GetGadgets mocks base method.
func (m *MockCore) GetGadgets() []core.Gadget {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGadgets")
	ret0, _ := ret[0].([]core.Gadget)
	return ret0
}

// GetGadgets indicates an expected call of GetGadgets.
func (mr *MockCoreMockRecorder) GetGadgets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGadgets", reflect.TypeOf((*MockCore)(nil).GetGadgets))
}

// GetPlayerLastAction mocks base method.
func (m *MockCore) GetPlayerLastAction() info.LastAction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerLastAction")
	ret0, _ := ret[0].(info.LastAction)
	return ret0
}

// GetPlayerLastAction indicates an expected call of GetPlayerLastAction.
func (mr *MockCoreMockRecorder) GetPlayerLastAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerLastAction", reflect.TypeOf((*MockCore)(nil).GetPlayerLastAction))
}

// IgnoreBurstEnergy mocks base method.
func (m *MockCore) IgnoreBurstEnergy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IgnoreBurstEnergy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IgnoreBurstEnergy indicates an expected call of IgnoreBurstEnergy.
func (mr *MockCoreMockRecorder) IgnoreBurstEnergy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IgnoreBurstEnergy", reflect.TypeOf((*MockCore)(nil).IgnoreBurstEnergy))
}

// IsDamageMode mocks base method.
func (m *MockCore) IsDamageMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDamageMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDamageMode indicates an expected call of IsDamageMode.
func (mr *MockCoreMockRecorder) IsDamageMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDamageMode", reflect.TypeOf((*MockCore)(nil).IsDamageMode))
}

// IsHitlagEnabled mocks base method.
func (m *MockCore) IsHitlagEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHitlagEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHitlagEnabled indicates an expected call of IsHitlagEnabled.
func (mr *MockCoreMockRecorder) IsHitlagEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHitlagEnabled", reflect.TypeOf((*MockCore)(nil).IsHitlagEnabled))
}

// KillEnemy mocks base method.
func (m *MockCore) KillEnemy(i int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "KillEnemy", i)
}

// KillEnemy indicates an expected call of KillEnemy.
func (mr *MockCoreMockRecorder) KillEnemy(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillEnemy", reflect.TypeOf((*MockCore)(nil).KillEnemy), i)
}

// Log mocks base method.
func (m *MockCore) Log() glog.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(glog.Logger)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockCoreMockRecorder) Log() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockCore)(nil).Log))
}

// PlayerAirborne mocks base method.
func (m *MockCore) PlayerAirborne() info.AirborneSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerAirborne")
	ret0, _ := ret[0].(info.AirborneSource)
	return ret0
}

// PlayerAirborne indicates an expected call of PlayerAirborne.
func (mr *MockCoreMockRecorder) PlayerAirborne() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerAirborne", reflect.TypeOf((*MockCore)(nil).PlayerAirborne))
}

// PlayerCurrentState mocks base method.
func (m *MockCore) PlayerCurrentState() info.AnimationState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerCurrentState")
	ret0, _ := ret[0].(info.AnimationState)
	return ret0
}

// PlayerCurrentState indicates an expected call of PlayerCurrentState.
func (mr *MockCoreMockRecorder) PlayerCurrentState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerCurrentState", reflect.TypeOf((*MockCore)(nil).PlayerCurrentState))
}

// PlayerDashLockout mocks base method.
func (m *MockCore) PlayerDashLockout() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerDashLockout")
	ret0, _ := ret[0].(bool)
	return ret0
}

// PlayerDashLockout indicates an expected call of PlayerDashLockout.
func (mr *MockCoreMockRecorder) PlayerDashLockout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerDashLockout", reflect.TypeOf((*MockCore)(nil).PlayerDashLockout))
}

// PlayerRemainingDashCD mocks base method.
func (m *MockCore) PlayerRemainingDashCD() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerRemainingDashCD")
	ret0, _ := ret[0].(int)
	return ret0
}

// PlayerRemainingDashCD indicates an expected call of PlayerRemainingDashCD.
func (mr *MockCoreMockRecorder) PlayerRemainingDashCD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerRemainingDashCD", reflect.TypeOf((*MockCore)(nil).PlayerRemainingDashCD))
}

// PlayerStam mocks base method.
func (m *MockCore) PlayerStam() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerStam")
	ret0, _ := ret[0].(float64)
	return ret0
}

// PlayerStam indicates an expected call of PlayerStam.
func (mr *MockCoreMockRecorder) PlayerStam() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerStam", reflect.TypeOf((*MockCore)(nil).PlayerStam))
}

// PlayerSwapCD mocks base method.
func (m *MockCore) PlayerSwapCD() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerSwapCD")
	ret0, _ := ret[0].(int)
	return ret0
}

// PlayerSwapCD indicates an expected call of PlayerSwapCD.
func (mr *MockCoreMockRecorder) PlayerSwapCD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerSwapCD", reflect.TypeOf((*MockCore)(nil).PlayerSwapCD))
}

// PlayerTarget mocks base method.
func (m *MockCore) PlayerTarget() core.Character {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerTarget")
	ret0, _ := ret[0].(core.Character)
	return ret0
}

// PlayerTarget indicates an expected call of PlayerTarget.
func (mr *MockCoreMockRecorder) PlayerTarget() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerTarget", reflect.TypeOf((*MockCore)(nil).PlayerTarget))
}

// PlayerUseStam mocks base method.
func (m *MockCore) PlayerUseStam(amount float64, a info.Action) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayerUseStam", amount, a)
}

// PlayerUseStam indicates an expected call of PlayerUseStam.
func (mr *MockCoreMockRecorder) PlayerUseStam(amount, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerUseStam", reflect.TypeOf((*MockCore)(nil).PlayerUseStam), amount, a)
}

// QueueAttack mocks base method.
func (m *MockCore) QueueAttack(qa info.QueueAttack) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueAttack", qa)
}

// QueueAttack indicates an expected call of QueueAttack.
func (mr *MockCoreMockRecorder) QueueAttack(qa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueAttack", reflect.TypeOf((*MockCore)(nil).QueueAttack), qa)
}

// QueueAttackEvent mocks base method.
func (m *MockCore) QueueAttackEvent(ae *info.AttackEvent, dmgDelay int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueAttackEvent", ae, dmgDelay)
}

// QueueAttackEvent indicates an expected call of QueueAttackEvent.
func (mr *MockCoreMockRecorder) QueueAttackEvent(ae, dmgDelay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueAttackEvent", reflect.TypeOf((*MockCore)(nil).QueueAttackEvent), ae, dmgDelay)
}

// QueueAttackWithSnap mocks base method.
func (m *MockCore) QueueAttackWithSnap(snap info.Snapshot, qa info.QueueAttack) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueAttackWithSnap", snap, qa)
}

// QueueAttackWithSnap indicates an expected call of QueueAttackWithSnap.
func (mr *MockCoreMockRecorder) QueueAttackWithSnap(snap, qa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueAttackWithSnap", reflect.TypeOf((*MockCore)(nil).QueueAttackWithSnap), snap, qa)
}

// Rand mocks base method.
func (m *MockCore) Rand() *rand.Rand {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rand")
	ret0, _ := ret[0].(*rand.Rand)
	return ret0
}

// Rand indicates an expected call of Rand.
func (mr *MockCoreMockRecorder) Rand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rand", reflect.TypeOf((*MockCore)(nil).Rand))
}

// RemoveGadget mocks base method.
func (m *MockCore) RemoveGadget(key keys.Target) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveGadget", key)
}

// RemoveGadget indicates an expected call of RemoveGadget.
func (mr *MockCoreMockRecorder) RemoveGadget(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGadget", reflect.TypeOf((*MockCore)(nil).RemoveGadget), key)
}

// SetDefaultTarget mocks base method.
func (m *MockCore) SetDefaultTarget(key keys.Target) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefaultTarget", key)
}

// SetDefaultTarget indicates an expected call of SetDefaultTarget.
func (mr *MockCoreMockRecorder) SetDefaultTarget(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultTarget", reflect.TypeOf((*MockCore)(nil).SetDefaultTarget), key)
}

// SetEnemyPos mocks base method.
func (m *MockCore) SetEnemyPos(i int, pos geometry.Point) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnemyPos", i, pos)
}

// SetEnemyPos indicates an expected call of SetEnemyPos.
func (mr *MockCoreMockRecorder) SetEnemyPos(i, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnemyPos", reflect.TypeOf((*MockCore)(nil).SetEnemyPos), i, pos)
}

// SetPlayerAirborne mocks base method.
func (m *MockCore) SetPlayerAirborne(a info.AirborneSource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPlayerAirborne", a)
}

// SetPlayerAirborne indicates an expected call of SetPlayerAirborne.
func (mr *MockCoreMockRecorder) SetPlayerAirborne(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlayerAirborne", reflect.TypeOf((*MockCore)(nil).SetPlayerAirborne), a)
}

// SetPlayerDashCD mocks base method.
func (m *MockCore) SetPlayerDashCD(lockout bool, cd int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPlayerDashCD", lockout, cd)
}

// SetPlayerDashCD indicates an expected call of SetPlayerDashCD.
func (mr *MockCoreMockRecorder) SetPlayerDashCD(lockout, cd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlayerDashCD", reflect.TypeOf((*MockCore)(nil).SetPlayerDashCD), lockout, cd)
}

// SetPlayerDirectionToClosestEnemy mocks base method.
func (m *MockCore) SetPlayerDirectionToClosestEnemy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPlayerDirectionToClosestEnemy")
}

// SetPlayerDirectionToClosestEnemy indicates an expected call of SetPlayerDirectionToClosestEnemy.
func (mr *MockCoreMockRecorder) SetPlayerDirectionToClosestEnemy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlayerDirectionToClosestEnemy", reflect.TypeOf((*MockCore)(nil).SetPlayerDirectionToClosestEnemy))
}

// SetPlayerPos mocks base method.
func (m *MockCore) SetPlayerPos(pos geometry.Point) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPlayerPos", pos)
}

// SetPlayerPos indicates an expected call of SetPlayerPos.
func (mr *MockCoreMockRecorder) SetPlayerPos(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlayerPos", reflect.TypeOf((*MockCore)(nil).SetPlayerPos), pos)
}

// SetPlayerSwapICD mocks base method.
func (m *MockCore) SetPlayerSwapICD(cd int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPlayerSwapICD", cd)
}

// SetPlayerSwapICD indicates an expected call of SetPlayerSwapICD.
func (mr *MockCoreMockRecorder) SetPlayerSwapICD(cd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlayerSwapICD", reflect.TypeOf((*MockCore)(nil).SetPlayerSwapICD), cd)
}

// StatusDuration mocks base method.
func (m *MockCore) StatusDuration(status string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusDuration", status)
	ret0, _ := ret[0].(int)
	return ret0
}

// StatusDuration indicates an expected call of StatusDuration.
func (mr *MockCoreMockRecorder) StatusDuration(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusDuration", reflect.TypeOf((*MockCore)(nil).StatusDuration), status)
}

// Tasks mocks base method.
func (m *MockCore) Tasks() task.Tasker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tasks")
	ret0, _ := ret[0].(task.Tasker)
	return ret0
}

// Tasks indicates an expected call of Tasks.
func (mr *MockCoreMockRecorder) Tasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tasks", reflect.TypeOf((*MockCore)(nil).Tasks))
}
